version: '3.9'
services:
  tor:
    image: dperson/torproxy
    restart: always
    ports:
      - "9050:9050"
    command: -a
  web:
    build: .
    ports:
      - "5000:5000"
    depends_on:
      - tor
